### ISSUE TITLE
개발 외에 코드와 설정 파일이 올라와 있습니다.

### ISSUE THREAD

**Issue by dimsssss** [dimsssss/cloneAlice-front#1]
현재 저희가 개발하지 않는 코드와 설정파일이 올라와 있는데요. gitignore에 추가 부탁드립니다.

**Comment by foranything** [comment]
어떤 파일 말씀하시는건가요?
`favicon.ico` 이나 `serviceWorker` 같은 파일이요?

**Comment by dimsssss** [comment]
아니요. 제가 nodemodule디렉토리랑 개인 IDE설정 파일을 보았다고 생각했는데  잘못봤나봅니다.
